#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = Path(
    os.environ.get(
        "CHUMMER_BLAZOR_WORKBENCH_POLISH_STAGED_PROOF_PATH",
        REPO_ROOT / ".codex-studio" / "published" / "BLAZOR_WORKBENCH_POLISH_STAGED_PROOF.generated.json",
    )
)

CHECKS = [
    {
        "id": "product_workbench_task_dock",
        "path": "Chummer.Blazor/Components/Pages/Preview.razor",
        "tokens": [
            "Compatibility route task dock",
            "Chummer Online task dock",
            "Chummer Online task shortcuts",
            "data-workbench-polish=\"task-dock\"",
            "Task dock",
            "data-workbench-dock-action=\"character-roster\"",
            "Character Roster",
            "ChummerOnlineRosterHref",
            "ChummerOnlineRosterAppHref",
            "private const string AppRouteQueryPrefix = $\"{AppRouteSegment}?{CommandQueryName}=\"",
            "data-workbench-dock-action=\"start-new\"",
            "data-workbench-dock-action=\"open-existing\"",
            "data-workbench-dock-action=\"build-lab\"",
            "data-workbench-dock-action=\"gear\"",
            "data-workbench-dock-action=\"save-as\"",
            "data-workbench-dock-action=\"export\"",
            "data-workbench-dock-action=\"print\"",
            "data-workbench-dock-action=\"downloads\"",
            "data-workbench-dock-action=\"support\"",
            "BuildPreviewHref",
            "href=\"@DownloadsHref\"",
            "private const string DownloadsHref = \"/downloads/\"",
            "href=\"@ContactHref\"",
            "private const string ContactHref = \"/contact\"",
            "href=\"@HomeHref\"",
            "private const string HomeHref = \"home\"",
            "href=\"@AppHref\"",
            "private const string AppHref = \"app\"",
            "href=\"@ShowcaseHref\"",
            "private const string ShowcaseHref = \"showcase\"",
            "href=\"@DocsHref\"",
            "private const string DocsHref = \"/docs/\"",
            "private const string NewCharacterCommand = \"new_character\"",
            "private const string OpenCharacterCommand = \"open_character\"",
            "private const string NewCharacterOriginCommand = \"new_character_origin\"",
            "private const string CharacterRosterCommand = \"character_roster\"",
            "private const string SaveCharacterCommand = \"save_character\"",
            "private const string SaveCharacterAsCommand = \"save_character_as\"",
            "private const string ExportCharacterCommand = \"export_character\"",
            "private const string PrintCharacterCommand = \"print_character\"",
            "private const string XmlEditorCommand = \"xml_editor\"",
            "private const string SwitchRulesetCommand = \"switch_ruleset\"",
            "private const string GlobalSettingsCommand = \"global_settings\"",
            "private const string CharacterSettingsCommand = \"character_settings\"",
            "command: NewCharacterCommand",
            "command: OpenCharacterCommand",
            "command: NewCharacterOriginCommand",
            "command: CharacterRosterCommand",
            "command: SaveCharacterCommand",
            "command: SaveCharacterAsCommand",
            "command: ExportCharacterCommand",
            "command: PrintCharacterCommand",
            "command: XmlEditorCommand",
            "command: SwitchRulesetCommand",
            "command: GlobalSettingsCommand",
            "command: CharacterSettingsCommand",
            "BuildWorkbenchCommandHref(SaveCharacterAsCommand)",
            "BuildWorkbenchCommandHref(ExportCharacterCommand)",
            "BuildWorkbenchCommandHref(ExportCharacterCommand, \"download\")",
            "BuildWorkbenchCommandHref(PrintCharacterCommand)",
            "private const string AppRouteSegment = \"app\"",
            "private const string WorkbenchRouteSegment = \"workbench\"",
            "private const string PreviewRouteSegment = \"preview\"",
            "private const string HostedAppRoute = \"/blazor/app\"",
            "private const string HostedWorkbenchRoute = \"/blazor/workbench\"",
            "AppRouteMarker",
            "WorkbenchRouteMarker",
            "IsAppRoute ? AppRouteSegment : WorkbenchRouteSegment",
            ": \"preview\"",
            "path-base-safe relative hrefs",
            "Compatibility route status",
            "Preview tools status",
            "Preview tools guidance",
            "Use this route for saved compatibility links",
            "Use this route for preview and result-state tools",
            "older compatibility bookmarks and shared links working",
            "user-facing browser client remains Chummer Online at /blazor/app",
            "preview tools, startup deep links, and browser result-state checks",
            "href=\"home\"",
            "href=\"app\"",
            "Compatibility route",
            "href=\"workbench\"",
            "href=\"preview\"",
            "Preview tools",
            "Open preview tools",
            "href=\"showcase\"",
            "href=\"health\"",
        ],
    },
    {
        "id": "scoped_visual_design",
        "path": "Chummer.Blazor/Components/Pages/Preview.razor.css",
        "tokens": [
            ".browser-workbench-task-dock",
            ".browser-workbench-task-dock-copy",
            ".browser-workbench-task-dock-actions",
            "Chummer Online theme polish",
            "not a default preview page",
            "Final Chummer Online visual theme layer",
            "--app-gold",
            "--app-gold-soft",
            "#ffd46f",
            "--app-green-soft",
            "#8ff0bc",
            "--app-muted-strong",
            "--app-line-cool",
            "--app-shadow",
            "--app-radius",
            "overflow-x: clip",
            ".browser-preview-shell::before",
            "background-size: 3.4rem 3.4rem",
            ".browser-preview-banner",
            ".browser-preview-shell section[class*=\"browser-workbench-\"]",
            ".browser-preview-actions a",
            ".browser-preview-actions a[href=\"/downloads/\"]",
            ".browser-preview-actions a[href=\"/docs/\"]",
            ".browser-preview-actions a[href=\"/downloads/\"]:focus-visible",
            ".browser-preview-actions a[href=\"/docs/\"]:focus-visible",
            ".browser-preview-status-label",
            "border-radius: 999px",
            ".browser-preview-shell section[class*=\"browser-workbench-\"]::after",
            "linear-gradient(180deg, var(--app-gold), var(--app-green))",
            "linear-gradient(90deg, var(--app-gold), var(--app-green))",
            ".browser-workbench-density-options label:has(input:checked)",
            "accent-color: var(--app-green)",
            ".browser-preview-shell code",
            "[data-workbench-dock-action=\"character-roster\"]",
            "[data-workbench-dock-action=\"start-new\"]",
            "[data-workbench-dock-action=\"open-existing\"]",
            "min-height: 3.6rem",
            "outline-color: rgba(6, 17, 13, 0.86)",
            "transform: translateY(-1px)",
            "radial-gradient(circle at 9% 0%",
            "@media (prefers-reduced-motion: reduce)",
            "@media (max-width: 720px)",
            "Final Chummer Online theme pass",
            "--app-rust",
            "#ffd46f",
            "#76aeca",
            "background-size: 4.25rem 4.25rem",
            ".browser-preview-title",
            ".browser-preview-route-label",
            "linear-gradient(135deg, #ffe29a, #8ff0bc 82%)",
            "box-shadow: 0 0 0 5px rgba(143, 240, 188, 0.15)",
            "transition: border-color 160ms ease",
            "Final Chummer Online motion pass",
            "@keyframes chummer-command-deck-reveal",
            "animation: chummer-command-deck-reveal 420ms cubic-bezier(0.2, 0.78, 0.2, 1) both",
            "animation-delay: 180ms",
            "animation: none",
            "Final route-token pass",
            "font-variant-ligatures: none",
            "min-height: 1.45rem",
            "text-transform: uppercase",
            "Final mobile route-token pass",
            "@media (max-width: 520px)",
            "overflow-wrap: anywhere",
            "Final keyboard route-token pass",
            ".browser-preview-shell code:focus-visible",
            "outline: 3px solid rgba(255, 212, 111, 0.78)",
            "Final high-contrast route-token pass",
            "@media (prefers-contrast: more)",
            "border-color: rgba(255, 247, 227, 0.82)",
        ],
    },
    {
        "id": "status_strip_route_chrome",
        "path": "Chummer.Blazor/Components/Shell/StatusStrip.razor",
        "tokens": [
            "@using Microsoft.AspNetCore.Components",
            "data-status-route-family",
            "BuildRouteFamily",
            "BuildRouteLabel",
            "Chummer Online",
            "Chummer Online overview",
            "Preview/support tools",
            "Chummer Online compatibility",
            "Route:",
            "Route: {BuildRouteLabel()} | Dossier:",
            "Navigation.Uri",
            "private const string ChummerAppRouteFamily = \"chummer_app\"",
            "private const string WorkbenchCompatibilityRouteFamily = \"workbench_compat\"",
            "private const string BrowserClientRouteFamily = \"browser_client\"",
        ],
    },
    {
        "id": "shell_chrome_boundary_dossier_command_labels",
        "path": "Chummer.Presentation/UiKit/ShellChromeBoundary.cs",
        "tokens": [
            "[\"new_character\"] = \"New Runner\"",
            "[\"open_character\"] = \"Open Dossier...\"",
            "[\"open_for_printing\"] = \"Open Dossier for Printing...\"",
            "[\"open_for_export\"] = \"Open Dossier for Export...\"",
            "[\"save_character\"] = \"Save Dossier\"",
            "[\"save_character_as\"] = \"Save Dossier As...\"",
            "[\"print_character\"] = \"Print Dossier...\"",
            "[\"export_character\"] = \"Export Dossier...\"",
            "[\"character_settings\"] = \"Dossier Settings\"",
            "[\"character_roster\"] = \"Character Roster\"",
        ],
    },
    {
        "id": "tool_strip_command_chrome",
        "path": "Chummer.Blazor/Components/Shell/ToolStrip.razor",
        "tokens": [
            "classic-tool-strip",
            "aria-label=\"Chummer actions\"",
            "FormatToolStripLabel",
            "NewCharacterCommandId => \"New\"",
            "OpenCharacterCommandId => \"Open\"",
            "SaveCharacterCommandId => \"Save\"",
            "SaveCharacterAsCommandId => \"Save As\"",
            "PrintCharacterCommandId => \"Print\"",
            "GlobalSettingsCommandId => \"Options\"",
            "ReportBugCommandId => \"Bug\"",
            "private const string NewCharacterCommandId = \"new_character\"",
            "private const string OpenCharacterCommandId = \"open_character\"",
            "private const string SaveCharacterCommandId = \"save_character\"",
            "private const string SaveCharacterAsCommandId = \"save_character_as\"",
            "private const string PrintCharacterCommandId = \"print_character\"",
            "private const string GlobalSettingsCommandId = \"global_settings\"",
            "private const string ReportBugCommandId = \"report_bug\"",
        ],
    },
    {
        "id": "desktop_shell_tool_strip_order",
        "path": "Chummer.Blazor/Components/Layout/DesktopShell.razor.cs",
        "tokens": [
            "PreferredToolStripCommandOrder",
            "private const string SaveCharacterCommandId = \"save_character\"",
            "private const string PrintCharacterCommandId = \"print_character\"",
            "private const string CopyCommandId = \"copy\"",
            "private const string NewCharacterCommandId = \"new_character\"",
            "private const string OpenCharacterCommandId = \"open_character\"",
            "private const string CloseWindowCommandId = \"close_window\"",
            "SaveCharacterCommandId",
            "PrintCharacterCommandId",
            "CopyCommandId",
            "NewCharacterCommandId",
            "OpenCharacterCommandId",
            "CloseWindowCommandId",
        ],
    },
    {
        "id": "open_workspace_tree_dossier_copy",
        "path": "Chummer.Blazor/Components/Shell/OpenWorkspaceTree.razor",
        "tokens": [
            "data-testid=\"open-workspace-tree\"",
            "private const string NoOpenDossiersMessage = \"No open dossiers.\"",
            "private const string CloseDossierLabel = \"Close dossier\"",
            "private const string OpenDossierLabelPrefix = \"Open dossier\"",
            "<p class=\"hint\">@NoOpenDossiersMessage</p>",
            "title=\"@BuildOpenDossierTitle(workspaceLabel)\"",
            "aria-label=\"@BuildOpenDossierTitle(workspaceLabel)\"",
            "aria-label=\"@CloseDossierLabel\"",
            "title=\"@CloseDossierLabel\"",
            "OpenWorkspaceRequested",
            "CloseWorkspaceRequested",
        ],
    },
    {
        "id": "mdi_strip_dossier_copy",
        "path": "Chummer.Blazor/Components/Shell/MdiStrip.razor",
        "tokens": [
            "class=\"mdi-strip\"",
            "private const string CloseDossierLabel = \"Close dossier\"",
            "title=\"@CloseDossierLabel\"",
            "aria-label=\"@CloseDossierLabel\"",
            "OpenWorkspaceRequested",
            "CloseWorkspaceRequested",
            "BuildWorkspaceStripEmptyState",
            "BuildWorkspaceTitle",
        ],
    },
    {
        "id": "ruleset_catalog_dossier_shell_fallback_copy",
        "path": "Chummer.Presentation/Rulesets/RulesetUiDirectiveCatalog.cs",
        "tokens": [
            "OpenWorkspaceLabel: \"Open dossier\"",
            "ResumeLaneSummary: \"Resume the current dossier after ruleset and runtime status are loaded.\"",
            "WorkspaceFollowThroughLabel: \"Open dossier details\"",
            "UngroundedHomeSummary: \"the first restored dossier still needs runtime status before build, rules, and export tools are ready.\"",
            "GroundedHomeSummary: \"shared shell selected; restore a ruleset-specific dossier to continue.\"",
            "Restore a dossier before running build, import, export, or print actions.",
            "RulesetDefaults.Sr5 => \"SR5 Roster\"",
            "RulesetDefaults.Sr5 => \"No open SR5 dossier\"",
            "dossier {workspaceId} is {saveState}.",
        ],
    },
    {
        "id": "metadata_panel_dossier_copy",
        "path": "Chummer.Blazor/Components/Shell/MetadataPanel.razor",
        "tokens": [
            "class=\"panel metadata\"",
            "private const string DossierIdLabel = \"Dossier ID\"",
            "private const string DossierMetadataHeading = \"Dossier Metadata\"",
            "private const string UpdateDossierMetadataLabel = \"Update Dossier Metadata\"",
            "private const string SaveDossierLabel = \"Save Dossier\"",
            "private const string LoadDossierLabel = \"Load Dossier\"",
            "private const string DossierIdPlaceholder = \"Dossier id\"",
            "<h2>@DossierMetadataHeading</h2>",
            "@DossierIdLabel",
            "@UpdateDossierMetadataLabel",
            "@SaveDossierLabel",
            "@LoadDossierLabel",
            "placeholder=\"@DossierIdPlaceholder\"",
            "LoadWorkspaceRequested",
            "LoadWorkspaceId",
        ],
    },
    {
        "id": "build_lab_handoff_dossier_copy",
        "path": "Chummer.Blazor/Components/Shared/BuildLabHandoffPanel.razor",
        "tokens": [
            "Campaign continuity: no governed campaign dossier is attached yet, so the handoff still lands on the living dossier first.",
            "Chosen variant stays attached to dossier-safe and campaign-safe outputs.",
            "Outputs: 1 dossier or campaign-safe output is already attached to the handoff.",
            "BuildLabHandoffProjection",
        ],
    },
    {
        "id": "desktop_home_build_explain_dossier_copy",
        "path": "Chummer.Presentation/Overview/DesktopHomeBuildExplainProjector.cs",
        "tokens": [
            "first claimed dossier",
            "No dossier is pinned yet.",
            "add one real dossier",
            "No dossier return target is pinned yet.",
            "first dossier",
            "dossier summary",
            "cached dossier summary only",
            "once a dossier is ready",
            "for this dossier on runtime",
            "no active runtime profile is loaded for this dossier yet",
            "aligned with the current dossier",
            "first grounded dossier still needs to land",
        ],
    },
    {
        "id": "desktop_home_campaign_dossier_copy",
        "path": "Chummer.Presentation/Overview/DesktopHomeCampaignProjector.cs",
        "tokens": [
            "No signed-in campaign dossier is loaded yet.",
            "open your dossier",
            "your campaign dossier",
            "current campaign dossier line up",
            "calmer dossier digest",
            "no current campaign dossier return target is pinned yet",
            "grounded campaign dossier",
            "local-only dossier",
            "create one campaign dossier",
            "campaign dossier you reopen from this home cockpit",
        ],
    },
    {
        "id": "overview_presenter_dossier_feedback_copy",
        "path": "Chummer.Presentation/Overview/CharacterOverviewPresenter.Persistence.cs",
        "tokens": [
            "No dossier loaded.",
            "Dossier saved.",
            "UpdateMetadataAsync",
            "SaveAsync",
            "DownloadAsync",
            "ExportAsync",
            "PrintAsync",
        ],
    },
    {
        "id": "overview_rendering_dossier_feedback_copy",
        "path": "Chummer.Presentation/Overview/CharacterOverviewPresenter.WorkspaceRendering.cs",
        "tokens": [
            "No dossier loaded.",
            "LoadSectionAsync",
            "RenderSummaryAction",
            "RenderValidateAction",
        ],
    },
    {
        "id": "overview_mutation_dossier_feedback_copy",
        "path": "Chummer.Presentation/Overview/CharacterOverviewPresenter.WorkspaceMutations.cs",
        "tokens": [
            "No dossier loaded.",
            "Dossier download failed.",
            "ApplyWorkspaceXmlMutationAsync",
        ],
    },
    {
        "id": "overview_command_dossier_feedback_copy",
        "path": "Chummer.Presentation/Overview/CharacterOverviewPresenter.Commands.cs",
        "tokens": [
            "Dossier action is required.",
            "No dossier loaded.",
            "Unsupported dossier action kind",
            "ExecuteWorkspaceActionAsync",
            "SelectTabAsync",
        ],
    },
    {
        "id": "overview_shell_dossier_feedback_copy",
        "path": "Chummer.Presentation/Overview/CharacterOverviewPresenter.cs",
        "tokens": [
            "Restored {session.OpenWorkspaces.Count} dossier(s).",
            "CreateShellOverviewFeedback",
            "OpenWorkspaces",
        ],
    },
    {
        "id": "overview_dispatcher_dossier_feedback_copy",
        "path": "Chummer.Presentation/Overview/OverviewCommandDispatcher.cs",
        "tokens": [
            "No dossier loaded.",
            "Dossier reset complete.",
            "No open dossier to close.",
            "refresh_character",
            "close_all",
            "close_window",
        ],
    },
    {
        "id": "overview_lifecycle_dossier_feedback_copy",
        "path": "Chummer.Presentation/Overview/WorkspaceOverviewLifecycleCoordinator.cs",
        "tokens": [
            "Dossier id is required.",
            "Dossier '{workspaceId.Value}' is already active.",
            "Closed active dossier.",
            "Active dossier was already closed.",
            "Closed active dossier. Switched to",
            "Closed dossier '{workspaceId.Value}'.",
            "Dossier '{workspaceId.Value}' was already closed.",
        ],
    },
    {
        "id": "desktop_localization_default_dossier_copy",
        "path": "Chummer.Presentation/Overview/DesktopLocalizationCatalog.cs",
        "tokens": [
            "[\"desktop.shell.tool.campaign_workspace\"] = \"Campaign Dossier\"",
            "[\"desktop.shell.tool.save_workspace\"] = \"Save Dossier\"",
            "[\"desktop.shell.tool.close_active_workspace\"] = \"Close Active Dossier\"",
            "[\"desktop.shell.workspace_strip.summary\"] = \"Dossier: {0} (open: {1}, {2})\"",
            "[\"desktop.shell.workspace_strip.empty\"] = \"Dossier: none\"",
            "[\"desktop.shell.feedback.no_active_workspace\"] = \"State: no active dossier to close.\"",
            "[\"desktop.shell.feedback.campaign_workspace_reviewed\"] = \"State: campaign dossier reviewed.\"",
            "[\"desktop.home.section.recent_workspaces\"] = \"Recent dossiers\"",
            "[\"desktop.campaign.title\"] = \"Campaign dossier\"",
            "[\"desktop.campaign.heading\"] = \"Campaign dossier\"",
            "[\"desktop.campaign.restore.latest_workspace\"] = \"Latest local dossier: {0} . {1} UTC\"",
            "[\"desktop.install_link.button.open_work\"] = \"Open linked dossier\"",
            "[\"desktop.home.button.open_current_workspace\"] = \"Open Runner Dossier\"",
            "[\"desktop.home.button.open_current_campaign_workspace\"] = \"Open Campaign Dossier\"",
            "[\"desktop.home.button.open_workspace_followthrough\"] = \"Open Dossier Help\"",
            "[\"desktop.install_link.summary.next_safe_action_claimed\"] = \"Next step: open your dossier.\"",
            "[\"desktop.devices.context.access_claimed\"] = \"Support, updates, and dossier recovery are attached to this linked install.\"",
        ],
    },
    {
        "id": "desktop_dialog_factory_dossier_copy",
        "path": "Chummer.Presentation/Overview/DesktopDialogFactory.cs",
        "tokens": [
            "Apply runner profile metadata changes to the active dossier.",
            "Paste Chummer XML to import into a dossier.",
            "$\"Dossier: {workspace}\"",
            "new DesktopDialogField(\"workspace\", \"Dossier\"",
            "dossier mutation",
            "(no dossier)",
            "dossier available",
            "\"Saved Dossiers\"",
            "(\"Dossier\", \"inventory tab stays active\")",
            "(\"Dossier\", \"cyberware tab stays active\")",
            "(\"Dossier\", \"vehicle tab stays active\")",
            "(\"Dossier\", \"skills tab stays active\")",
            "(\"Dossier\", \"magic tab stays active\")",
            "(\"Dossier\", \"contacts tab stays active\")",
            "(\"Dossier\", \"qualities tab stays active\")",
        ],
    },
    {
        "id": "section_pane_browse_dossier_copy",
        "path": "Chummer.Blazor/Components/Shell/SectionPane.razor",
        "tokens": [
            "Browse Dossier",
            "data-browse-shell=\"@browseWorkspace.WorkspaceId\"",
            "BuildBrowseResultWindowLabel",
            "browseWorkspace.DialogTitle",
        ],
    },
    {
        "id": "showcase_campaign_dossier_copy",
        "path": "Chummer.Blazor/Components/Pages/Showcase.razor",
        "tokens": [
            "campaign dossier",
            "The campaign dossier keeps the downstream continuity target visible",
            "active compatibility fingerprint for the campaign dossier",
            "current dossier while the next promotion stays under review",
            "Shadow Ops dossier",
            "Shadow Ops dossier",
        ],
    },
    {
        "id": "status_strip_route_chrome_style",
        "path": "Chummer.Blazor/wwwroot/app.css",
        "tokens": [
            "Route-aware status strip chrome",
            ".classic-status-strip [data-status-route-family]",
            "data-status-route-family=\"chummer_app\"",
            "data-status-route-family=\"workbench_compat\"",
            "rgba(255, 212, 111, 0.36)",
            "rgba(143, 240, 188, 0.48)",
            "rgba(118, 174, 202, 0.48)",
            "@media (prefers-contrast: more)",
        ],
    },
    {
        "id": "release_truth_docs",
        "path": "docs/WORKBENCH_RELEASE_SIGNOFF.md",
        "tokens": [
            "workbench polish posture",
            "blazor-workbench-polish-staged-proof-check.sh",
            "preserving `/app` as the clean public Chummer Online route",
            "`/blazor/app` as the hosted app path",
            "`/blazor/preview` as the preview tools/result-state route",
            "keyboard-visible portal nav focus",
            "route-aware status strip chrome",
            "not a hosted or Docker browser execution receipt",
        ],
    },
    {
        "id": "proof_contract_docs",
        "path": "docs/BLAZOR_WORKBENCH_POLISH_STAGED_PROOF.md",
        "tokens": [
            "Chummer Online and compatibility route polish",
            "cohesive slate/amber/mint/blue browser-client palette",
            "startup command links for roster/new/import/origin flows derive from local command constants",
            "`character_roster`, `new_character`, `open_character`, or `new_character_origin` command strings",
            "output command links for save/save-as/export/print flows derive from local command constants",
            "setup and rules command links for XML editor, ruleset, global settings, and dossier settings derive from local command constants",
            "final amber/mint/blue Chummer Online color pass",
            "warm gold, mint, and blue accents",
            "app and compatibility route do not read as a default preview page",
            "`/app` remains the clean public Chummer Online route",
            "`/blazor/app` remains the hosted app path",
            "`/blazor/preview` remains the preview tools and result-state route",
            "broad app-shell card treatment for every `browser-workbench-*` strip",
            "deliberate density-control styling with mint radio accents",
            "themed inline route/code tokens",
            "route-token app chrome treatment",
            "mobile route-token wrapping",
            "keyboard-visible route-token focus",
            "high-contrast route-token affordances",
            "pill-style route and status labels",
            "route-aware status strip chrome",
            "route-state status pill styling",
            "data-status-route-family",
            "left-edge gold-to-mint section accents",
            "keyboard-visible primary startup focus",
            "reduced-motion-safe command-deck reveal animation",
            "primary task-dock treatment for Character Roster, New runner, and Open/import",
            "mobile touch-friendly primary task-dock actions",
            "primary task-dock focus outline",
            "portal-handoff header nav treatment",
            "keyboard-visible portal-handoff header nav focus",
            "not hosted browser execution proof",
        ],
    },
    {
        "id": "parity_goal_docs",
        "path": "docs/BLAZOR_WEB_CLIENT_PARITY_GOAL.md",
        "tokens": [
            "staged hosted workbench polish posture",
            "Task dock",
            "Character Roster",
            "start, edit, output, and portal handoff",
            "preserving `/app` as the clean public Chummer Online route",
            "`/blazor/app` as the hosted app path",
            "`/blazor/preview` as the preview tools/result-state route",
            "primary Character Roster, New runner, and Open/import actions",
            "final amber/mint/blue Chummer Online theme layer",
            "reduced-motion-safe command-deck reveal",
            "route-token app chrome treatment",
            "mobile route-token wrapping",
            "keyboard-visible route-token focus",
            "high-contrast route-token affordances",
            "route-aware status strip chrome",
            "route-state status pill styling",
            "mobile top-edge section accents",
        ],
    },
    {
        "id": "docs_index_contract",
        "path": "docs/BLAZOR_WEB_CLIENT_DOCS_INDEX.md",
        "tokens": [
            "source-staged Chummer Online and compatibility route polish contract",
            "compatibility route boundary where `/app` remains the clean public Chummer Online route",
            "`/blazor/app` remains the hosted app path",
            "`/blazor/preview` remains the preview tools/result-state route",
            "primary Character Roster/New runner/Open-import startup actions",
            "startup command links for roster/new/import/origin flows derived from local command constants",
            "keyboard-visible focus",
            "mobile touch posture",
            "portal-handoff header nav treatment",
            "keyboard-visible portal nav focus",
            "slate/amber/mint/blue app theme",
            "refined amber/mint/blue app theme pass",
            "route-token app chrome treatment",
            "mobile route-token wrapping",
            "keyboard-visible route-token focus",
            "high-contrast route-token affordances",
            "route-aware status strip chrome",
            "route-state status pill styling",
        ],
    },
    {
        "id": "status_utility_reporting",
        "path": "scripts/print_blazor_public_edge_proof_status.py",
        "tokens": [
            "WORKBENCH_POLISH_STAGED_PROOF",
            "workbench_polish_staged_status",
            "workbench_polish_staged_source_checks",
            "source_alignment_only_not_browser_execution",
            "source_alignment_only_not_browser_execution_chummer_app_theme_primary_startup_mobile_portal_nav_motion",
        ],
    },
]


def read_text(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8-sig")


def main() -> int:
    checks = []
    failures = []

    for check in CHECKS:
        path = check["path"]
        tokens = check["tokens"]
        try:
            text = read_text(path)
        except FileNotFoundError:
            failures.append(f"{path}: missing file")
            checks.append({**check, "status": "failed", "missing_tokens": tokens})
            continue

        missing_tokens = [token for token in tokens if token not in text]
        status = "failed" if missing_tokens else "passed"
        if missing_tokens:
            failures.append(f"{path}: missing {', '.join(missing_tokens)}")
        checks.append(
            {
                "id": check["id"],
                "path": path,
                "status": status,
                "required_token_count": len(tokens),
                "missing_tokens": missing_tokens,
            }
        )

    receipt = {
        "contract_name": "chummer6-ui.blazor_workbench_polish_staged_proof",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "failed" if failures else "passed",
        "proof_tier": "source_staged_no_browser_execution",
        "route_lane": "chummer_app_and_proof_compatible_blazor_workbench",
        "expected_routes": ["/blazor/app", "/blazor/workbench"],
        "checks": checks,
        "failures": failures,
        "notes": [
            "This receipt only proves that Chummer Online and compatibility route polish source, style, status, and docs agree.",
            "The status utility reports this as app theme, primary startup, mobile posture, portal navigation, and reduced-motion-safe command-deck motion source alignment.",
            "It is not a substitute for hosted Playwright execution proof or Docker self-host proof.",
            "Do not use this receipt to claim desktop-equivalent browser workflow parity.",
        ],
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")

    if failures:
        print("\n".join(failures))
        return 1

    print(f"blazor_workbench_polish_staged_proof:ok {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
