#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = Path(
    os.environ.get(
        "CHUMMER_BLAZOR_WORKBENCH_ROSTER_HIERARCHY_STAGED_PROOF_PATH",
        REPO_ROOT / ".codex-studio" / "published" / "BLAZOR_WORKBENCH_ROSTER_HIERARCHY_STAGED_PROOF.generated.json",
    )
)

CHECKS = [
    {
        "id": "presentation_roster_hierarchy_contract",
        "path": "Chummer.Presentation/Overview/RosterHierarchyState.cs",
        "tokens": [
            "RosterHierarchyState",
            "RosterHierarchyFolderState",
            "RosterHierarchyMoveIntentState",
            "MovesFilesOnlyAfterConfirmation",
            "RosterHierarchyDeletePolicies",
            "move_children_to_inbox_first",
            "RosterHierarchyStateJson",
            "RosterHierarchyMetadata",
            "FormatVersion",
            "GeneratedSource",
            "StagedPreferenceSource",
            "ActiveTableFolderId",
            "ActiveTableFolderName",
            "SavedRunnersFolderId",
            "SavedRunnersFolderName",
            "InboxFolderId",
            "InboxFolderName",
            "WatchLinksFolderId",
            "WatchLinksFolderName",
            "UserDirectoriesLabel",
            "SystemDirectoriesLabel",
            "Normalize",
            "TryDeserialize",
            "IsUsable",
        ],
    },
    {
        "id": "presentation_roster_hierarchy_preferences",
        "path": "Chummer.Presentation/Overview/DesktopPreferenceState.cs",
        "tokens": [
            "RosterHierarchyJson",
            "string RosterHierarchyJson = \"\"",
        ],
    },
    {
        "id": "presentation_roster_hierarchy_preference_normalization",
        "path": "Chummer.Presentation/Overview/DesktopPreferenceStateRuntime.cs",
        "tokens": [
            "RosterHierarchyJson = NormalizeRosterHierarchyJson",
            "NormalizeRosterHierarchyJson",
            "RosterHierarchyStateJson.Normalize",
        ],
    },
    {
        "id": "presentation_character_roster_hierarchy",
        "path": "Chummer.Presentation/Overview/DesktopDialogFactory.cs",
        "tokens": [
            "rosterCustomFolders",
            "rosterHierarchyStatus",
            "BuildRosterHierarchyStatus",
            "Enter/Space select or drop; Escape clears source",
            "rosterFolderName",
            "rosterTargetFolder",
            "BuildRosterFolderOptions",
            "Choose a directory or type a directory id/name for nesting and moves",
            "rosterSourceFolder",
            "Choose a custom directory or type a directory id/name for rename, delete, and nesting",
            "IncludeSystemFolders",
            "rosterSourceItem",
            "Move Dossier to Directory",
            "Create Roster Directory",
            "Rename Roster Directory",
            "Delete Roster Directory",
            "Open Roster Folder",
            "Create Roster Folder",
            "Configure Roster Folder",
            "Roster Entries",
            "Create custom roster directory",
            "Undo last roster move",
            "Save dossier to roster folder",
            "configure a roster folder first",
            "Reorder Character Tree",
            "Reset Character Layout",
            "Character Roster",
            "Group dossiers into your own folders",
            "drag dossiers or custom directories through the tree",
            "Drag dossier onto directory: preview move",
            "Keyboard: Enter/Space selects source, Enter/Space on directory drops, Escape clears source",
            "Custom Directories",
            "Default Directory",
            "RosterHierarchyMetadata.UserDirectoriesLabel",
            "RosterHierarchyMetadata.SystemDirectoriesLabel",
            "user's hierarchy",
            "layout metadata follows owner and dossier scope",
            "delete custom directory moves dossier/link items to {RosterHierarchyMetadata.InboxFolderName} and reparents child directories",
            "directory drops cannot target their own descendants",
            "dragged row wins before selected-dossier fallback",
            "globalRosterHierarchyJson",
            "preferences.RosterHierarchyJson",
            "rosterHierarchySource",
            "hierarchySource = RosterHierarchyMetadata.GeneratedSource",
            "hierarchySource = RosterHierarchyMetadata.StagedPreferenceSource",
            "TryDeserializeRosterHierarchyState",
            "RosterHierarchyJson = DesktopDialogFieldValueParser.GetValue",
        ],
    },
    {
        "id": "presentation_roster_command_dispatch",
        "path": "Chummer.Presentation/Overview/DialogCoordinator.cs",
        "tokens": [
            "create_roster_group",
            "rename_roster_group",
            "delete_roster_group",
            "move_runner_to_group",
            "reorder_roster_tree",
            "reset_roster_hierarchy",
            "StageCharacterRosterHierarchyMutation",
            "ResetCharacterRosterHierarchy",
            "Roster layout reset to generated grouping",
            "CreateRosterFolder",
            "DeleteRosterFolder",
            "Moved {movedItemCount} dossier/link item(s) to {RosterHierarchyMetadata.InboxFolderName}",
            "MoveRosterRunner",
            "ResolveRosterSourceItem",
            "ExtractRosterLineLabel",
            "RosterHierarchyItemKinds.Workspace",
            "LastIndexOf(\" [\"",
            "Nested roster folder",
            "IsRosterFolderDescendant",
            "cannot be nested under one of its own child folders",
            "PublishCharacterRosterDialog(context, nextPreferences",
            "Created roster folder",
            "RosterHierarchyJson",
            "RosterHierarchyStateJson.Serialize",
            "RosterHierarchyStateJson.TryDeserialize",
        ],
    },
    {
        "id": "blazor_dialog_markup",
        "path": "Chummer.Blazor/Components/Shell/DialogHost.razor",
        "tokens": [
            "data-roster-hierarchy-field",
            "private const string RosterFieldPrefix = \"roster\"",
            "private const string RosterCustomFoldersFieldId = \"rosterCustomFolders\"",
            "private const string RosterHierarchyStatusFieldId = \"rosterHierarchyStatus\"",
            "private const string RosterSystemFolderScope = \"system\"",
            "private const string RosterCustomFolderScope = \"custom\"",
            "private const string RosterMoveRunnerToGroupCommand = \"move_runner_to_group\"",
            "private const string RosterReorderTreeCommand = \"reorder_roster_tree\"",
            "RosterSystemFolderMarker",
            "RosterCustomFolderMarker",
            "rosterHierarchyStatus",
            "dialog-roster-tree",
            "dialog-roster-list",
            "data-roster-hierarchy-toolbar",
            "dialog-roster-toolbar",
            "dialog-roster-mode",
            "BuildRosterHierarchyToolbarTitle",
            "BuildRosterHierarchyToolbarSummary",
            "BuildRosterHierarchyContainerLabel",
            "Ready to organize",
            "Move pending",
            "data-roster-drag-root",
            "data-roster-line-kind",
            "data-roster-folder-scope",
            "data-roster-source-item",
            "data-roster-drop-action",
            "data-roster-accepts-drop-kinds",
            "BuildRosterHierarchyLineKind",
            "BuildRosterHierarchyFolderScope",
            "BuildRosterHierarchySourceItem",
            "BuildRosterHierarchyDropAction",
            "BuildRosterHierarchyAcceptedDropKinds",
            "runner watched-file folder-shortcut custom-directory",
            "\"watched-file\"",
            "\"folder-shortcut\"",
            "\"system\"",
            "\"custom\"",
            "@ondragstart",
            "@ondragend",
            "ClearRosterDragSource",
            "_rosterMouseDragSourceLine",
            "_rosterKeyboardSourceLine",
            "RosterActiveSourceLine",
            "@ondrop",
            "DialogRosterDropIntent",
            "SourceItem",
            "BuildRosterHierarchyLineKind(field, sourceLine)",
            "BuildRosterHierarchyFolderScope(field, sourceLine)",
            "BuildRosterHierarchyFolderScope(field, line)",
            "RosterDropRequested",
            "reorder_roster_tree",
            "IsRosterHierarchyField",
            "IsRosterDropTargetLine",
            "is-drop-target",
            "BuildRosterHierarchyLineTitle",
            "aria-label",
            "aria-describedby",
            "RosterKeyboardHintId",
            "dialog-roster-keyboard-hint",
            "role=\"note\"",
            "RosterKeyboardStatusId",
            "BuildRosterHierarchyLineDescriptionId",
            "BuildRosterHierarchyContainerRole",
            "BuildRosterHierarchyContainerLabel",
            "aria-orientation",
            "BuildRosterHierarchyContainerOrientation",
            "BuildRosterHierarchyLineRole",
            "treeitem",
            "aria-level",
            "BuildRosterHierarchyLineLevel",
            "aria-selected",
            "BuildRosterHierarchyLineSelected",
            "return null;",
            "aria-expanded",
            "BuildRosterHierarchyLineExpanded",
            "aria-keyshortcuts",
            "BuildRosterHierarchyLineKeyShortcuts",
            "Enter Space Escape",
            "BuildRosterHierarchyLineTabIndex",
            "HandleRosterLineKeyDownAsync",
            "Escape",
            "Enter",
            "is-drag-source",
            "is-keyboard-source",
            "is-mouse-source",
            "dialog-roster-keyboard-status",
            "IsRosterKeyboardStatusHost",
            "RosterActiveSourceMode",
            "RosterActiveSourceInstruction",
            "RosterKeyboardHintId",
            "RosterKeyboardStatusId",
            "BuildRosterKeyboardDomId",
            "NormalizeRosterDomId",
            "source selected:",
            "Drop a runner/link row here to move it into this roster directory, or drop a custom directory here to nest it.",
            "Drag this roster row to a directory.",
            "line.Contains(RosterSystemFolderMarker, StringComparison.OrdinalIgnoreCase)",
            "Press Enter or Space on a directory to drop, or Escape to clear.",
            "Drop on a directory to move or nest, or release outside a directory to cancel.",
            "role=\"status\"",
            "aria-atomic=\"true\"",
            "Keyboard: Enter/Space selects this source; Escape clears it.",
            "Keyboard: Enter or Space selects a source row, Enter or Space on a directory drops it, Escape clears the source.",
            "Keyboard: Enter/Space drops the selected source here.",
            "Moves are virtual metadata only until explicitly committed.",
            "BuildRosterHierarchyLineClass",
        ],
    },
    {
        "id": "blazor_home_roster_entry",
        "path": "Chummer.Blazor/Components/Pages/Home.razor",
        "tokens": [
            "data-home-hero-action=\"@ExploreChummerOnlineHeroAction\"",
            "private const string ExploreChummerOnlineHeroAction = \"explore-chummer-online\"",
            "Explore Chummer Online",
            "Chummer Online for real dossier work.",
            "Chummer Online, rules guidance",
            "Chummer Online promise",
            "Live Chummer Online",
            "Open Chummer Online",
            "See Chummer Online tour",
            "Workflow trust",
            "private const string TourSectionId = \"tour\"",
            "private const string BoundariesSectionId = \"boundaries\"",
            "private const string TrustSectionId = \"trust\"",
            "TourAnchor => $\"#{TourSectionId}\"",
            "BoundariesAnchor => $\"#{BoundariesSectionId}\"",
            "TrustAnchor => $\"#{TrustSectionId}\"",
            "href=\"@TrustAnchor\"",
            "id=\"@TrustSectionId\"",
            "Jump to trust section",
            "Roster entry:",
            "private const string AppRoute = \"app\"",
            "private const string HomeRoute = \"home\"",
            "private const string DownloadsRoute = \"/downloads/\"",
            "private const string DocsRoute = \"/docs/\"",
            "private const string PublicRootRoute = \"/\"",
            "private const string PublicDocsRoute = \"/docs\"",
            "private const string ShowcaseRoute = \"showcase\"",
            "private const string RosterCommandQueryName = \"command\"",
            "private const string ContactPortraitRevisionMediaPath = \"/media/portraits/contact-portrait-revision.png\"",
            "private const string ContactPortraitCurrentMediaPath = \"/media/portraits/contact-portrait-current.png\"",
            "private const string RouteRecapClipMediaPath = \"/media/routes/route-recap-clip.mp4\"",
            "private const string DesktopShellRouteAnchorTestId = \"desktop-shell-route-anchor\"",
            "private const string FlagshipMediaSampleAnchorTestId = \"flagship-media-sample-anchor\"",
            "private const string CampaignSpineShowcaseAnchorTestId = \"campaign-spine-showcase-anchor\"",
            "private const string ContactPortraitRevisionAssetId = \"asset-portraits-01\"",
            "private const string ContactPortraitCurrentAssetId = \"asset-dossier-01\"",
            "private const string RouteRecapClipAssetId = \"asset-news-01\"",
            "private const string PrimaryNavigationAriaLabel = \"Primary\"",
            "private const string ChummerOnlinePromiseAriaLabel = \"Chummer Online promise\"",
            "private const string CharacterRosterCommand = \"character_roster\"",
            'RosterRoute => $"{AppRoute}?{RosterCommandQueryName}={CharacterRosterCommand}"',
            'PublicRosterRoute => $"/{RosterRoute}"',
            "href=\"@HomeRoute\"",
            "href=\"@DownloadsRoute\"",
            "href=\"@DocsRoute\"",
            "href=\"@ShowcaseRoute\"",
            "@PublicDocsRoute",
            "@PublicRootRoute",
            "aria-label=\"@PrimaryNavigationAriaLabel\"",
            "aria-label=\"@ChummerOnlinePromiseAriaLabel\"",
            "src=\"@ContactPortraitRevisionMediaPath\"",
            "src=\"@ContactPortraitCurrentMediaPath\"",
            "src=\"@RouteRecapClipMediaPath\"",
            "data-testid=\"@DesktopShellRouteAnchorTestId\"",
            "data-testid=\"@FlagshipMediaSampleAnchorTestId\"",
            "data-testid=\"@CampaignSpineShowcaseAnchorTestId\"",
            "data-asset-id=\"@ContactPortraitRevisionAssetId\"",
            "data-asset-id=\"@ContactPortraitCurrentAssetId\"",
            "data-asset-id=\"@RouteRecapClipAssetId\"",
        ],
    },
    {
        "id": "blazor_home_roster_entry_style",
        "path": "Chummer.Blazor/Components/Pages/Home.razor.css",
        "tokens": [
            "public-surface-reveal",
            "@media (prefers-reduced-motion: reduce)",
            "@media (prefers-contrast: more)",
            ".public-preview::before",
            "background-size: 3.2rem 3.2rem",
            "--chummer-gold: #ffd46f",
            "--chummer-green: #8ff0bc",
            "--chummer-blue: #76aeca",
        ],
    },
    {
        "id": "blazor_app_roster_startup_route",
        "path": "Chummer.Blazor/Components/Pages/Preview.razor",
        "tokens": [
            "data-chummer-app-startup-command",
            "IsCharacterRosterCommand",
            "private const string NewCharacterOriginCommand = \"new_character_origin\"",
            "private const string CharacterRosterCommand = \"character_roster\"",
            "private const string WorkspaceQueryName = \"workspace\"",
            "private const string LegacyRunnerQueryName = \"runner\"",
            "[SupplyParameterFromQuery(Name = WorkspaceQueryName)]",
            "[SupplyParameterFromQuery(Name = LegacyRunnerQueryName)]",
            "ResolvedWorkspace => !string.IsNullOrWhiteSpace(Workspace) ? Workspace : Runner",
            "query.Add($\"{WorkspaceQueryName}={Uri.EscapeDataString(workspace)}\")",
            "data-workbench-route-query=\"@WorkspaceQueryName\"",
            "command: CharacterRosterCommand",
            "string.Equals(Command, CharacterRosterCommand, StringComparison.OrdinalIgnoreCase)",
            "Chummer Online is opening directly into the Character Roster",
            "Character Roster",
            "Find, group, and organize existing dossiers.",
            "DemoStartupCommandId=\"@EffectiveStartupCommandId\"",
        ],
    },
    {
        "id": "blazor_shell_smoke_public_branding",
        "path": "scripts/e2e-ui.sh",
        "tokens": [
            "Chummer Online for real dossier work.",
            "Chummer Online marker not found in root page response.",
            "_framework/blazor.web.js",
            "Preview Chummer Online workflows without changing the public route.",
        ],
    },
    {
        "id": "blazor_roster_drag_drop_shell_bridge",
        "path": "Chummer.Blazor/Components/Layout/DesktopShell.Dialogs.cs",
        "tokens": [
            "OnDialogRosterDropAsync",
            "SourceFolder",
            "rosterSourceItem",
            "string.IsNullOrWhiteSpace(intent.SourceItem) ? intent.SourceLine : intent.SourceItem",
            "rosterSourceFolder",
            "rosterTargetFolder",
            "ExecuteDialogActionAsync(intent.ActionId",
            "SyncShellWorkspaceContextAsync",
        ],
    },
    {
        "id": "blazor_status_route_label_branding",
        "path": "Chummer.Blazor/Components/Shell/StatusStrip.razor",
        "tokens": [
            "ChummerAppRouteFamily => \"Chummer Online\"",
            "HomeRouteFamily => \"Chummer Online overview\"",
            "PreviewRouteFamily => \"Preview/support tools\"",
            "WorkbenchCompatibilityRouteFamily => \"Chummer Online compatibility\"",
            "Route: {BuildRouteLabel()} | Dossier:",
            "data-status-route-family=\"@BuildRouteFamily()\"",
            "return ChummerAppRouteFamily",
            "return WorkbenchCompatibilityRouteFamily",
            "private const string ChummerAppRouteFamily = \"chummer_app\"",
            "private const string WorkbenchCompatibilityRouteFamily = \"workbench_compat\"",
            "private const string BrowserClientRouteFamily = \"browser_client\"",
            "private const string AppPathSuffix = \"/app\"",
            "private const string WorkbenchPathSuffix = \"/workbench\"",
            "private const string BlazorPathSuffix = \"/blazor\"",
        ],
    },
    {
        "id": "blazor_startup_shell_chummer_online_copy",
        "path": "Chummer.Blazor/Components/Shell/SectionPane.razor",
        "tokens": [
            "Continue Chummer Online",
            "The Character Roster remains the primary route.",
            "No recent dossiers yet. Use <strong>Open Dossier...</strong> to restore a dossier from disk.",
            "Restore this Chummer Online dossier continuation.",
            "Select a tab to render a dossier section.",
            "Chummer Utilities",
            "private const string SaveCharacterCommandId = \"save_character\"",
            "private const string OpenCharacterCommandId = \"open_character\"",
            "private const string NewCharacterCommandId = \"new_character\"",
            "private const string NewCharacterOriginCommandId = \"new_character_origin\"",
            "private const string CharacterRosterCommandId = \"character_roster\"",
            "private const string MasterIndexCommandId = \"master_index\"",
            "OpenCharacterCommandId",
            "NewCharacterCommandId",
            "NewCharacterOriginCommandId",
            "CharacterRosterCommandId",
            "MasterIndexCommandId",
        ],
    },
    {
        "id": "blazor_dialog_style",
        "path": "Chummer.Blazor/wwwroot/app.css",
        "tokens": [
            ".dialog-field--roster-hierarchy",
            "content: \" preview\"",
            ".dialog-visual--roster-hierarchy",
            ".dialog-roster-toolbar",
            ".dialog-roster-mode",
            ".dialog-roster-line.is-draggable",
            ".dialog-roster-line.is-drop-target",
            'content: "drop directory"',
            ".dialog-roster-line.is-drag-source",
            ".dialog-roster-line.is-keyboard-source",
            ".dialog-roster-line.is-mouse-source",
            ".dialog-roster-keyboard-hint",
            ".dialog-roster-keyboard-status",
            ".dialog-roster-line:focus-visible",
            ".dialog-roster-line.is-selected",
            'data-roster-line-kind="directory"',
            'data-roster-folder-scope="system"',
            'data-roster-folder-scope="custom"',
            'content: "bucket"',
            'content: "folder"',
            'data-roster-line-kind="watched-file"',
            'data-roster-line-kind="folder-shortcut"',
            "Chummer web app theme polish",
            "--chummer-theme-gold: #ffd46f",
            "--chummer-theme-mint: #8ff0bc",
            "--chummer-theme-cyan: #76aeca",
            "data-roster-hierarchy-mode=\"keyboard\"",
            "data-roster-hierarchy-mode=\"mouse\"",
            "roster pending organization changes",
            "rgba(255, 212, 111, 0.34)",
            "rgba(143, 240, 188, 0.72)",
            "box-shadow: 0 0 0 3px rgba(143, 240, 188, 0.16)",
        ],
    },
    {
        "id": "release_truth_docs",
        "path": "docs/WORKBENCH_RELEASE_SIGNOFF.md",
        "tokens": [
            "Character Roster now also carries custom hierarchy posture",
            "custom roster directories",
            "non-destructive metadata mutation",
            "polished amber/mint/blue hierarchy treatment",
            "pending organization status",
            "roster-first public home hero route pills",
            "reduced-motion-safe reveal",
            "high-contrast affordances",
            "mobile-softened grid density",
            "`rosterHierarchySource` disclosure",
            "system library buckets that remain filing drop targets but are not draggable source directories",
            "clears stale `rosterSourceFolder` for runner/link drops",
            "`data-roster-line-kind` and `data-roster-folder-scope`",
            "roster-directory organization affordances",
        ],
    },
    {
        "id": "parity_goal_docs",
        "path": "docs/BLAZOR_WEB_CLIENT_PARITY_GOAL.md",
        "tokens": [
            "Character Roster custom hierarchy posture",
            "custom roster directories and a hierarchy of the user's choosing",
            "user-created virtual folders, nested groups, drag/drop move intent",
            "non-destructive metadata mutation",
            "polished amber/mint/blue hierarchy treatment",
            "pending organization status",
            "roster-first public home hero route pills",
            "reduced-motion-safe reveal",
            "high-contrast affordances",
            "mobile-softened grid density",
            "Blazor drag/drop event bridge",
            "system library buckets as filing drop targets but not draggable source directories",
            "clears stale `rosterSourceFolder` for runner/link drops",
            "`data-roster-line-kind` and `data-roster-folder-scope`",
            "`rosterHierarchySource` disclosure",
            "before full hosted drag execution is claimed",
            "portal-generated public CTAs should use `/app?command=character_roster`",
            "Blazor-rendered internal links must use relative `app?command=character_roster`",
            "themed Character Roster hierarchy surfaces",
            "system library buckets as drop targets only",
        ],
    },
    {
        "id": "status_utility_reporting",
        "path": "scripts/print_blazor_public_edge_proof_status.py",
        "tokens": [
            "WORKBENCH_ROSTER_HIERARCHY_STAGED_PROOF",
            "workbench_roster_hierarchy_staged_status",
            "workbench_roster_hierarchy_staged_source_checks",
            "source_alignment_only_roster_directories_not_drag_drop_execution_or_filesystem_mutation_proof",
        ],
    },
    {
        "id": "docs_index_contract_link",
        "path": "docs/BLAZOR_WEB_CLIENT_DOCS_INDEX.md",
        "tokens": [
            "docs/BLAZOR_WORKBENCH_ROSTER_HIERARCHY_STAGED_PROOF.md",
            "custom dossier roster hierarchy posture",
            "DialogHost-local roster field-id, folder-scope, and drag/drop mutation command constants",
            "nested hierarchy of the user's choosing",
            "drag/drop move intent",
            "explicit `data-roster-line-kind` and `data-roster-folder-scope` selectors",
            "roster-first public home hero route pills",
            "reduced-motion-safe reveal",
            "high-contrast affordances",
            "mobile-softened grid density",
            "runtime boundary language",
            "polished amber/mint/blue hierarchy treatment",
            "pending organization status",
            "system library buckets as drop targets but not draggable source directories",
        ],
    },
    {
        "id": "contract_doc_index_requirement",
        "path": "docs/BLAZOR_WORKBENCH_ROSTER_HIERARCHY_STAGED_PROOF.md",
        "tokens": [
            "This staged proof keeps Chummer Online and /blazor/workbench sources aligned",
            "custom dossier roster hierarchy posture",
            "Documentation Index Requirement",
            "docs/BLAZOR_WEB_CLIENT_DOCS_INDEX.md",
            "custom roster directories and a hierarchy of the user's choosing",
            "System library buckets remain valid drop targets",
            "only user-created custom directories can be nested, renamed, reordered, or deleted",
            "system rows as bucket targets",
            "custom rows as folder targets",
            "runner rows as direct dossier items",
            "watched-file or shortcut rows as linked roster references",
            "`data-roster-line-kind` and `data-roster-folder-scope`",
            "top-level Blazor/Chummer Online docs map",
            "polished amber/mint/blue Chummer Online hierarchy treatment",
            "pending organization status",
            "derived from `AppRoute` and `CharacterRosterCommand` through `RosterRoute` and `PublicRosterRoute`",
            "Roster entry: /app?command=character_roster",
            "Public copy uses Trust and web-client tour language",
            "public title, brand subtitle, hero headline, promise label, live-client card, and footer use Chummer Online wording",
            "preserving `/app` as the clean route alias",
            "status strip also presents the clean route as Chummer Online",
            "keeping stable internal route-family ids such as `chummer_app` and `workbench_compat`",
            "recent entries restore Chummer Online dossier continuations",
            "support commands are grouped under Chummer Utilities",
            "normalized `SourceItem`, `SourceKind`, `SourceFolderScope`, and `TargetFolderScope` metadata",
            "Roster rows also expose `data-roster-source-item`, `data-roster-drop-action`, and `data-roster-accepts-drop-kinds`",
            "without parsing visual tree glyphs",
            "reduced-motion-safe public surface reveal",
            "high-contrast affordances",
            "mobile-softened grid density",
        ],
    },
]


def read_text(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def evaluate_check(check: dict) -> dict:
    content = read_text(check["path"])
    missing_tokens = [token for token in check["tokens"] if token not in content]
    return {
        "id": check["id"],
        "path": check["path"],
        "status": "passed" if not missing_tokens else "failed",
        "required_token_count": len(check["tokens"]),
        "missing_tokens": missing_tokens,
    }


def main() -> int:
    evaluated_checks = [evaluate_check(check) for check in CHECKS]
    failures = [check for check in evaluated_checks if check["status"] != "passed"]
    receipt = {
        "contract_name": "chummer6-ui.blazor_workbench_roster_hierarchy_staged_proof",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "failed" if failures else "passed",
        "proof_tier": "source_staged_no_browser_execution",
        "route_lane": "chummer_app_and_promoted_blazor_workbench",
        "expected_routes": [
            "/blazor/app?command=character_roster",
            "/blazor/workbench?command=character_roster",
        ],
        "checks": evaluated_checks,
        "failures": failures,
        "notes": [
            "This receipt only proves that the Character Roster directory hierarchy source, styling, status, and docs agree.",
            "RosterHierarchyStateJson is the shared Avalonia/web normalization and validation seam for staged roster hierarchy metadata.",
            "It is not a substitute for hosted browser execution, drag/drop mutation, durable layout persistence, filesystem moves, directory deletion, watched-file relocation, or external RosterHierarchyState storage.",
            "Do not use this receipt to claim complete roster persistence or browser execution parity.",
        ],
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    print(f"blazor_workbench_roster_hierarchy_staged_proof:{receipt['status']} {OUTPUT_PATH}")
    return 0 if not failures else 1


if __name__ == "__main__":
    raise SystemExit(main())
