#!/usr/bin/env python3
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = Path(
    os.environ.get(
        "CHUMMER_BLAZOR_PORTAL_INSTALLER_HANDOFF_STAGED_PROOF_PATH",
        REPO_ROOT / ".codex-studio" / "published" / "BLAZOR_PORTAL_INSTALLER_HANDOFF_STAGED_PROOF.generated.json",
    )
)

EXPECTED_ROUTES = [
    "/downloads/",
    "/downloads/releases.json",
    "/downloads/install/avalonia-linux-x64-installer",
    "/downloads/install/avalonia-win-x64-installer",
    "/downloads/install/blazor-desktop-linux-x64-installer",
    "/downloads/install/blazor-desktop-win-x64-installer",
    "/contact",
    "/status",
    "/help",
    "/app",
    "/blazor/",
    "/blazor/home",
    "/blazor/app",
    "/blazor/workbench",
]

CHECKS = [
    {
        "id": "hosted_public_edge_route_probe",
        "path": "scripts/e2e-public-edge.cjs",
        "tokens": [
            "/downloads/",
            "/downloads/releases.json",
            "/downloads/install/avalonia-linux-x64-installer",
            "/downloads/install/avalonia-win-x64-installer",
            "/downloads/install/blazor-desktop-linux-x64-installer",
            "/downloads/install/blazor-desktop-win-x64-installer",
            "/contact",
            "/status",
            "/help",
            "/app",
            "`${baseUrl}/app`",
            "/\\/blazor\\/app\\/?$/.test(response.url)",
            "/blazor/",
            "/blazor/home",
            "/blazor/app",
            "/blazor/workbench",
            "Download the current Windows installer.",
            "Download the current Linux DEB package.",
            'data-download-panel="desktop-downloads"',
            "--portal-gold: #ffd46f",
            "--portal-mint: #8ff0bc",
            "body::before",
            "background-size: 4.25rem 4.25rem",
            "@keyframes portal-surface-reveal",
            "animation: portal-surface-reveal .38s cubic-bezier(.2,.78,.2,1) both",
            'data-docs-panel="operator-openapi-explorer"',
            'data-portal-status-panel="release-availability"',
            'data-portal-contact-panel="support-handoff"',
            'aria-label="Status recovery actions"',
            'aria-label="Contact recovery actions"',
            "desktop-downloads-title",
            'aria-labelledby="desktop-downloads-title"',
            'aria-describedby="fallback-link"',
            'data-download-action="download-artifact"',
            "data-download-manifest-link",
            "Open raw releases manifest JSON",
            "data-download-fallback-guidance",
            "data-download-status=",
            "data-download-version=",
            "data-download-artifact-summary=",
            "data-download-install-route=",
            "data-download-raw-url=",
            'data-download-link-mode="raw-url"',
            "data-download-platform=",
            "data-download-platform-label",
            "published-download-description",
            "data-download-description",
            "aria-describedby=\"published-download-description\"",
            "direct download",
            "aria-label=",
            "data-install-route-public-route=",
            "data-install-route-link-mode=\"proof-required\"",
            "proof-required handoff",
            "data-install-route-posture-label",
            "data-install-route-promotion-label",
            "data-install-route-artifact-label",
            "compatibility-handoff-description",
            "data-install-route-description",
            "aria-describedby=\"compatibility-handoff-description\"",
            "decodedLocation",
            "installState=proof_required",
            "next=%2Fdownloads%2Finstall%2Fblazor-desktop-linux-x64-installer",
            "`${baseUrl}/downloads/?next=%2Fdownloads%2Finstall%2Fblazor-desktop-linux-x64-installer&installState=proof_required`",
            "data-install-state=\"proof_required\"",
            "data-install-next-route=",
            "/downloads/install/blazor-desktop-linux-x64-installer",
            "role=\"status\"",
            "aria-live=\"polite\"",
            "data-install-state-action=\"open-browser-app\"",
            "Open Chummer Online instead",
            'data-self-host-downloads-panel="docker-operator"',
            "self-host-downloads-title",
            'data-self-host-docker-command="docker compose --profile portal up -d"',
            'data-self-host-browser-app="{{WebUtility.HtmlEncode(PortalRoutes.PublicAppRoster)}}"',
            "Use /app?command=character_roster when installer proof is pending",
            "data-self-host-release-manifest=",
            "data-self-host-browser-app=",
            'data-self-host-installer-boundary="proof-required"',
            "payload?.paths?.['/help']",
            "payload?.paths?.['/app']",
            "payload?.paths?.['/contact']",
            "payload?.paths?.['/status']",
            "payload?.paths?.['/downloads/']",
            "payload?.paths?.['/downloads/releases.json']",
            "payload?.paths?.['/downloads/install/{artifactId}']",
            "/docs/docs.js",
            'data-openapi-download-route="true"',
            'data-openapi-installer-handoff-route="true"',
            'data-openapi-release-status-route="true"',
            'data-openapi-support-handoff-route="true"',
            'data-openapi-help-handoff-route="true"',
            'data-openapi-chummer-app-route="true"',
            'data-openapi-chummer-home-route="true"',
            'data-openapi-blazor-entry-route="true"',
            'data-portal-contact-panel="support-handoff"',
            'data-portal-contact-scenarios="installer-account-app"',
            'data-portal-contact-action="open-status"',
            'data-portal-contact-action="open-downloads"',
            'data-portal-contact-action="open-help"',
        ],
    },
    {
        "id": "self_host_portal_route_probe",
        "path": "scripts/e2e-portal.cjs",
        "tokens": [
            "/downloads/",
            "/downloads/releases.json",
            "/downloads/install/avalonia-linux-x64-installer",
            "/downloads/install/avalonia-win-x64-installer",
            "/downloads/install/blazor-desktop-linux-x64-installer",
            "/downloads/install/blazor-desktop-win-x64-installer",
            "/contact",
            "/status",
            "/help",
            "/app",
            "`${baseUrl}/app`",
            "/\\/blazor\\/app\\/?$/.test(response.url)",
            "/blazor/",
            "/blazor/home",
            "/blazor/app",
            "/blazor/workbench",
            'data-portal-home-action="explore-chummer-online"',
            "linear-gradient(135deg,#b9812f 0%,#ffd46f 58%,#fff2b4 100%)",
            'data-portal-status-panel="release-availability"',
            "--portal-gold: #ffd46f",
            "--portal-mint: #8ff0bc",
            "body::before",
            "background-size: 4.25rem 4.25rem",
            "@keyframes portal-surface-reveal",
            "animation: portal-surface-reveal .38s cubic-bezier(.2,.78,.2,1) both",
            'data-docs-panel="operator-openapi-explorer"',
            'data-portal-help-panel="handoff-guide"',
            'data-portal-contact-panel="support-handoff"',
            'aria-label="Status recovery actions"',
            'aria-label="Contact recovery actions"',
            "data-portal-status-availability=",
            "data-portal-status-release-status=",
            "data-portal-status-version=",
            "data-portal-status-artifact-count=",
            "data-portal-status-install-route-count=",
            'data-portal-status-boundary="source-manifest-backed"',
            'data-portal-status-action="open-downloads"',
            'data-portal-status-action="open-chummer-app"',
            "/app?command=character_roster",
            "static class PortalRoutes",
            "PublicAppRoster",
            "PublicAppSlash",
            "BlazorApp",
            "BlazorHome",
            "CharacterRosterCommand",
            "BlazorHomeSegment",
            'PublicAppRoster => $"{PublicApp}?command={CharacterRosterCommand}"',
            'data-portal-status-action="open-chummer-home"',
            'data-portal-status-action="open-help"',
            'data-portal-status-action="open-docs"',
            'data-download-panel="desktop-downloads"',
            "desktop-downloads-title",
            'aria-labelledby="desktop-downloads-title"',
            'aria-describedby="fallback-link"',
            'data-download-action="download-artifact"',
            "data-download-manifest-link",
            "Open raw releases manifest JSON",
            "data-download-fallback-guidance",
            "data-download-status=",
            "data-download-version=",
            "data-download-artifact-summary=",
            "data-download-install-route=",
            "data-download-raw-url=",
            'data-download-link-mode="raw-url"',
            "data-download-platform=",
            "data-download-platform-label",
            "published-download-description",
            "data-download-description",
            "aria-describedby=\"published-download-description\"",
            "direct download",
            "aria-label=",
            "data-install-route-public-route=",
            "data-install-route-link-mode=\"proof-required\"",
            "proof-required handoff",
            "data-install-route-posture-label",
            "data-install-route-promotion-label",
            "data-install-route-artifact-label",
            "compatibility-handoff-description",
            "data-install-route-description",
            "aria-describedby=\"compatibility-handoff-description\"",
            "decodedLocation",
            "installState=proof_required",
            "next=%2Fdownloads%2Finstall%2Fblazor-desktop-linux-x64-installer",
            "`${baseUrl}/downloads/?next=%2Fdownloads%2Finstall%2Fblazor-desktop-linux-x64-installer&installState=proof_required`",
            "data-install-state=\"proof_required\"",
            "data-install-next-route=",
            "/downloads/install/blazor-desktop-linux-x64-installer",
            "role=\"status\"",
            "aria-live=\"polite\"",
            "data-install-state-action=\"open-browser-app\"",
            "Open Chummer Online instead",
            'data-self-host-downloads-panel="docker-operator"',
            "self-host-downloads-title",
            'data-self-host-docker-command="docker compose --profile portal up -d"',
            "data-self-host-release-manifest=",
            "data-self-host-browser-app=",
            'data-self-host-installer-boundary="proof-required"',
            "payload?.paths?.['/help']",
            "payload?.paths?.['/app']",
            "payload?.paths?.['/contact']",
            "payload?.paths?.['/downloads/']",
            "payload?.paths?.['/downloads/releases.json']",
            "payload?.paths?.['/downloads/install/{artifactId}']",
            "/docs/docs.js",
            'data-openapi-download-route="true"',
            'data-openapi-installer-handoff-route="true"',
            'data-openapi-release-status-route="true"',
            'data-openapi-support-handoff-route="true"',
            'data-openapi-help-handoff-route="true"',
            'aria-label="Help recovery actions"',
            "payload?.paths?.['/status']",
            'data-openapi-chummer-app-route="true"',
            'data-openapi-chummer-home-route="true"',
            'data-openapi-blazor-entry-route="true"',
            'data-portal-contact-panel="support-handoff"',
            'data-portal-contact-context="self-host-fallback"',
            'data-portal-contact-scenarios="installer-account-app"',
            'data-portal-contact-scenario="installer-proof"',
            'data-portal-contact-scenario="account-recovery"',
            'data-portal-contact-scenario="browser-app"',
            'data-portal-contact-action="open-chummer-app"',
            "/app?command=character_roster",
            'data-portal-contact-action="open-chummer-home"',
            'data-portal-contact-action="open-status"',
            'data-portal-contact-action="open-downloads"',
            'data-portal-contact-action="open-help"',
            'data-portal-contact-action="open-docs"',
        ],
    },

    {
        "id": "self_host_release_receipt_metadata",
        "path": "scripts/e2e-portal.sh",
        "tokens": [
            "/downloads/install/avalonia-linux-x64-installer",
            "/downloads/",
            "/downloads/releases.json",
            "/downloads/install/blazor-desktop-linux-x64-installer",
            "/downloads/install/blazor-desktop-win-x64-installer",
            "/contact",
            "/status",
            "/help",
            "/blazor/home",
            "/blazor/app",
            "/blazor/workbench",
        ],
    },
    {
        "id": "portal_openapi_download_routes",
        "path": "Chummer.Portal/Program.cs",
        "tokens": [
            '["/downloads/"]',
            '["/downloads/releases.json"]',
            '["/downloads/install/{artifactId}"]',
            '["/app"]',
            '["/blazor/app"]',
            '["/blazor/home"]',
            '["/blazor/"]',
            '["/status"]',
            '["/contact"]',
            '["/help"]',
            "Read downloads shelf with published artifacts, proof-required handoff routes, and self-host operator guidance",
            "Resolve installer handoff from release metadata or return proof-required downloads guidance",
            "Read release availability and install handoff status",
            "Open support/contact handoff for installer, account, and Chummer Online help",
            "Open same-origin help handoff for Chummer Online, downloads, status, contact, and docs",
            "Chummer Online route discovery",
            "BuildDocsHtml(options)",
            "string appRosterUrl = WebUtility.HtmlEncode",
            "string appHomeUrl = WebUtility.HtmlEncode",
            'data-docs-panel="operator-openapi-explorer"',
            'data-docs-shortcuts="operator-recovery"',
            'aria-describedby="docs-shortcuts-description"',
            "data-docs-shortcuts-description",
            'data-docs-summary="openapi-load-state"',
            'role="status"',
            'aria-live="polite"',
            'data-docs-endpoints="openapi-route-list"',
            'role="list"',
            'aria-label="Documented portal routes"',
            'data-docs-endpoint-card="openapi-route"',
            "data-docs-endpoint-route",
            "data-docs-endpoint-family",
            "data-docs-endpoint-methods",
            "data-docs-endpoint-summary",
            'role="listitem"',
            'data-docs-action="open-chummer-app"',
            "/app?command=character_roster",
            "appRosterUrl",
            'data-docs-action="open-chummer-home"',
            "appHomeUrl",
            'data-docs-action="open-downloads"',
            'data-docs-action="open-status"',
            'data-docs-action="open-help"',
            'data-docs-action="open-contact"',
            'data-docs-action="open-openapi-json"',
            "--portal-gold: #ffd46f",
            "--portal-mint: #8ff0bc",
            "body::before",
            "background-size: 4.25rem 4.25rem",
            "@keyframes portal-surface-reveal",
            "animation: portal-surface-reveal .38s cubic-bezier(.2,.78,.2,1) both",
            "--portal-blue: #76aeca",
            "body::before { opacity: .26; background-size: 3.2rem 3.2rem; }",
            " (prefers-contrast: more)",
            "outline: 3px solid #fff8e8",
            "linear-gradient(180deg,#192026 0%,#10161a 50%,#080b0d 100%)",
            "body::before",
            "background-size: 4.25rem 4.25rem",
            "@keyframes portal-surface-reveal",
            "animation: portal-surface-reveal .38s cubic-bezier(.2,.78,.2,1) both",
            "linear-gradient(135deg,#b9812f 0%,#ffd46f 58%,#fff2b4 100%)",
            "@media (prefers-reduced-motion: reduce)",
            "Open the user-facing Chummer Online browser client",
            "Open the clean public Chummer Online route alias",
            "BuildPublicAppRedirectUrl",
            "BuildBlazorAppUrl",
            "BuildBlazorHomeUrl",
            "PortalRoutes.BlazorAppSegment",
            "PortalRoutes.BlazorHomeSegment",
            "route === '{{PortalRoutes.PublicApp}}' || route === '{{PortalRoutes.BlazorApp}}'",
            "route === '{{PortalRoutes.BlazorHome}}'",
            "Open the Chummer Online product and self-host orientation page",
            "Open the stable Blazor browser entry that resolves into Chummer Online",
            'data-openapi-download-route="true"',
            'data-openapi-installer-handoff-route="true"',
            'data-openapi-release-status-route="true"',
            'data-openapi-support-handoff-route="true"',
            'data-openapi-help-handoff-route="true"',
            'data-openapi-chummer-app-route="true"',
            'data-openapi-chummer-home-route="true"',
            'data-openapi-blazor-entry-route="true"',
            "Chummer Online",
            "Chummer overview",
            "Stable browser entry",
            ".route-family",
            ".endpoint-summary",
            "operationSummary",
            "escapeHtml",
            "escapeHtml(method.toUpperCase())",
        ],
    },
    {
        "id": "portal_home_chummer_app_routes",
        "path": "Chummer.Portal/Program.cs",
        "tokens": [
            "BuildPortalHomeHtml",
            "Explore Chummer Online, downloads, and support from one self-hosted edge.",
            "Start in the character roster, continue into the browser client",
            "PortalRoutes.PublicApp",
            "PortalRoutes.PublicAppRoster",
            "PortalRoutes.CharacterRosterCommand",
            "appRosterUrl",
            "Explore Chummer Online",
            'data-portal-home-action="explore-chummer-online"',
            "Open Chummer Online",
            "Open Chummer overview",
            'aria-label="Chummer browser routes"',
            'data-portal-home-route="chummer-app-roster"',
            "Open character roster",
            "/app?command=character_roster",
            'href="{{appUrl}}"',
            "BuildPublicUrl(options.BlazorUrl, \"home\")",
            "Open Chummer Online",
            "Open Chummer overview",
            "Chummer browser routes",
            ".route-pills a:hover",
            'data-portal-home-route="chummer-app"',
            'data-portal-home-route="chummer-home"',
            'data-portal-home-route="downloads"',
            "Get desktop client",
            "@media (prefers-reduced-motion: reduce)",
        ],
    },
    {
        "id": "blazor_home_roster_first_root_redirect",
        "path": "Chummer.Blazor/Components/Pages/Home.razor",
        "tokens": [
            '@page "/"',
            '@page "/home"',
            "Chummer Online",
            'data-home-hero-action="explore-chummer-online"',
            "Explore Chummer Online",
            "Navigation.NavigateTo(RosterRoute, replace: true)",
            'private const string AppRoute = "app"',
            'private const string RosterCommandQueryName = "command"',
            'private const string CharacterRosterCommand = "character_roster"',
            'private static string RosterRoute => $"{AppRoute}?{RosterCommandQueryName}={CharacterRosterCommand}"',
            'private static string PublicRosterRoute => $"/{RosterRoute}"',
        ],
    },
    {
        "id": "portal_playwright_roster_first_cta",
        "path": "scripts/e2e-portal-playwright.cjs",
        "tokens": [
            'a.cta[href="/app?command=character_roster"][data-portal-home-action="explore-chummer-online"]',
            "portal home Chummer Online roster CTA",
            "Explore Chummer Online",
        ],
    },
    {
        "id": "portal_help_surface",
        "path": "Chummer.Portal/Program.cs",
        "tokens": [
            'app.MapGet("/help"',
            "BuildHelpHtml",
            'data-portal-help-panel="handoff-guide"',
            'aria-label="Help recovery actions"',
            ".help-card:hover",
            "@media (prefers-reduced-motion: reduce)",
            "portal-help-title",
            'data-portal-help-context="self-host-first"',
            'data-portal-help-action="open-chummer-app"',
            "appRosterUrl",
            "?command=character_roster",
            'data-portal-help-action="open-chummer-home"',
            'data-portal-help-action="open-downloads"',
            'data-portal-help-action="open-status"',
            'data-portal-help-action="open-contact"',
            'data-portal-help-action="open-docs"',
            'data-portal-help-boundary="source-guidance-only"',
            'data-openapi-help-handoff-route="true"',
        ],
    },
    {
        "id": "portal_status_surface",
        "path": "Chummer.Portal/Program.cs",
        "tokens": [
            'app.MapGet("/status"',
            "BuildStatusHtml",
            'data-portal-status-panel="release-availability"',
            "Current release",
            "The build, platforms, and current state in one place.",
            "data-portal-status-availability",
            "data-portal-status-release-status",
            "data-portal-status-version",
            "data-portal-status-artifact-count",
            "data-portal-status-install-route-count",
            'data-portal-status-boundary="source-manifest-backed"',
            'aria-label="Status recovery actions"',
            ".handoff-actions a:hover",
            "@media (prefers-reduced-motion: reduce)",
            'data-portal-status-action="open-downloads"',
            'data-portal-status-action="open-chummer-app"',
            "appRosterUrl",
            "?command=character_roster",
            'data-portal-status-action="open-help"',
            'data-portal-status-action="open-docs"',
            "This status page is backed by the local releases.json manifest.",
        ],
    },
    {
        "id": "portal_contact_surface",
        "path": "Chummer.Portal/Program.cs",
        "tokens": [
            "BuildContactHtml",
            'data-portal-contact-panel="support-handoff"',
            "portal-contact-title",
            'data-portal-contact-context="self-host-fallback"',
            'data-portal-contact-public-route="chummer.run/contact"',
            'data-portal-contact-scenarios="installer-account-app"',
            'data-portal-contact-scenario="installer-proof"',
            'data-portal-contact-scenario="account-recovery"',
            'data-portal-contact-scenario="browser-app"',
            'aria-label="Contact recovery actions"',
            ".handoff-actions a:hover",
            "@media (prefers-reduced-motion: reduce)",
            'data-portal-contact-action="open-chummer-app"',
            "appRosterUrl",
            "?command=character_roster",
            'data-portal-contact-action="open-status"',
            'data-portal-contact-action="open-downloads"',
            'data-portal-contact-action="open-help"',
            'data-portal-contact-action="open-docs"',
        ],
    },
    {
        "id": "portal_known_install_route_resolver",
        "path": "Chummer.Portal/Program.cs",
        "tokens": [
            "ReleaseInstallRouteSummary",
            "CollectInstallRoutes",
            "publicInstallRoute",
            "Uri.EscapeDataString(expectedPublicInstallRoute)",
            "Uri.EscapeDataString(knownInstallRoute.InstallPosture)",
            "next={encodedNextRoute}&installState={encodedInstallState}",
            "proof_required",
        ],
    },
    {
        "id": "downloads_install_state_guidance",
        "path": "Chummer.Portal/Program.cs",
        "tokens": [
            'data-download-action="download-artifact"',
            'data-download-action="open-chummer-app"',
            "appRosterUrl",
            "?command=character_roster",
            'data-download-kicker="chummer-release-shelf"',
            "Downloads handoff actions",
            "Install native Chummer when you need desktop file-system behavior",
            "@media (prefers-reduced-motion: reduce)",
            "outline: 3px solid rgba(137,224,179,.68)",
            "id=\"published-download-artifacts\"",
            "data-download-list=\"published-artifacts\"",
            "data-download-count",
            "Published artifacts:",
            'data-download-panel="desktop-downloads"',
            "desktop-downloads-title",
            'aria-labelledby="desktop-downloads-title"',
            'aria-describedby="fallback-link"',
            "data-download-manifest-link",
            "Open raw releases manifest JSON",
            "data-download-fallback-guidance",
            "data-download-status",
            "data-download-version",
            "data-download-artifact-summary",
            "data-download-empty=\"true\"",
            "aria-labelledby=\"published-download-artifacts\"",
            "id=\"published-download-description\"",
            "data-download-description",
            "Published artifacts are direct raw downloads from releases.json",
            "aria-describedby=\"published-download-description\"",
            "data-download-artifact",
            "data-download-platform",
            "data-download-platform-label",
            "data-download-artifact-label",
            "artifact id pending",
            "data-download-raw-url",
            "data-download-install-route",
            "data-download-link-mode",
            'data-download-link-mode="raw-url"',
            "data-download-link-mode-label",
            "direct download",
            'aria-label="{WebUtility.HtmlEncode($"{download.Label} for {download.Platform} direct download")}"',
            'href="{WebUtility.HtmlEncode(download.Url)}"',
            "raw-url",
            "download.PublicInstallRoute",
            "BuildDownloadsInstallStatePanel",
            "data-install-state=\"proof_required\"",
            "data-install-next-route=",
            "requested-installer-route",
            "role=\"status\"",
            "aria-live=\"polite\"",
            "installer proof is still required",
            "context.Request.Query[\"installState\"]",
            "context.Request.Query[\"next\"]",
            "data-install-state-action=\"open-browser-app\"",
            "app.MapGet(blazorHomeRoute, () => Results.Redirect(BuildPublicUrl(options.BlazorUrl, \"app\")))",
            "app.MapGet($\"{blazorHomeRoute}/\", () => Results.Redirect(BuildPublicUrl(options.BlazorUrl, \"app\")))",
            "BuildPublicUrl(options.BlazorUrl, \"app\")",
            "Compatibility handoff routes",
            'id="compatibility-handoff-routes"',
            'data-install-route-list="compatibility-handoff"',
            'class="compatibility routes"',
            ".compatibility routes",
            'aria-labelledby="compatibility-handoff-routes"',
            'id="compatibility-handoff-description"',
            "data-install-route-description",
            "Known fallback install routes stay visible here",
            'aria-describedby="compatibility-handoff-description"',
            "data-install-route-posture",
            "data-install-route-promotion",
            "data-install-route-public-route",
            'data-install-route-action="open-proof-required-route"',
            "data-install-route-artifact",
            "data-install-route-posture-label",
            "data-install-route-promotion-label",
            "data-install-route-artifact-label",
            "data-install-route-link-mode",
            'data-install-route-link-mode="proof-required"',
            "data-install-route-link-mode-label",
            "proof-required handoff",
            "artifact-pending",
            "artifact pending",
            "WebUtility.HtmlEncode(route.PublicInstallRoute)",
            'aria-label="{WebUtility.HtmlEncode($"{route.PublicInstallRoute} proof-required installer handoff")}"',
            "route.PromotionState",
            "summary.InstallRoutes",
            "List<ReleaseInstallRouteSummary> compatibilityRoutes",
            "data-install-route-count",
            "Compatibility routes:",
            "proof_capture_required",
            'string.Equals(route.InstallPosture, "proof_required", StringComparison.OrdinalIgnoreCase)',
            "route.PromotionState",
            "No compatibility handoff routes are listed in releases.json",
            'data-install-route-empty="true"',
            'data-self-host-downloads-panel="docker-operator"',
            "self-host-downloads-title",
            "Self-host operator lane",
            'data-self-host-docker-command="docker compose --profile portal up -d"',
            "Mount releases.json into the downloads volume before claiming installer availability.",
            "data-self-host-release-manifest",
            "data-self-host-browser-app",
            "Use /app?command=character_roster when installer proof is pending",
            'data-self-host-installer-boundary="proof-required"',
            "Proof-required compatibility routes stay visible",
            "@media (max-width: 720px)",
        ],
    },
    {
        "id": "portal_handoff_docs",
        "path": "docs/BLAZOR_PORTAL_INSTALLER_HANDOFF_PROOF.md",
        "tokens": EXPECTED_ROUTES + [
            "source-only",
            "same-origin through `Chummer.Portal`",
            "`installState=proof_required`",
            "`data-install-route-public-route`",
            "install posture is `proof_required` even when promotion state is absent",
            "self-host operator lane",
            "Chummer Online handoff action",
            "pointing at `/app?command=character_roster`",
            "roster workflow",
            "`/blazor/` resolves into Chummer Online and immediately opens the roster-first browser workflow through `app?command=character_roster`",
            'aria-label="Chummer browser routes"',
            "reduced-motion guard",
            "`data-self-host-downloads-panel=\"docker-operator\"`",
            "`docker compose --profile portal up -d`",
            "Mount `releases.json` into the downloads volume before claiming installer availability.",
            "`/status` must state current release availability.",
            "Chummer Online overview route",
            "The local OpenAPI contract at `/openapi/v1.json` must list `/app`, `/blazor/app`, `/blazor/home`, `/blazor/`",
            'data-docs-panel="operator-openapi-explorer"',
            'data-docs-shortcuts="operator-recovery"',
            'aria-describedby="docs-shortcuts-description"',
            "data-docs-shortcuts-description",
            'data-docs-summary="openapi-load-state"',
            'role="status"',
            'aria-live="polite"',
            'data-docs-endpoints="openapi-route-list"',
            'role="list"',
            'aria-label="Documented portal routes"',
            'data-docs-endpoint-card="openapi-route"',
            "data-docs-endpoint-route",
            "data-docs-endpoint-family",
            "data-docs-endpoint-methods",
            "data-docs-endpoint-summary",
            'role="listitem"',
            'data-docs-action="open-chummer-app"',
            "/app?command=character_roster",
            'data-docs-action="open-help"',
            'data-docs-action="open-openapi-json"',
            "clean public Chummer Online route",
            "operator shortcut opens the clean public `/app?command=character_roster`",
            "configured Blazor overview path",
            "reduced-motion handling for those shortcut controls",
            "top-level description names Chummer Online route discovery",
            "same polished Chummer Online slate/amber/mint/blue visual language",
            "`--portal-gold: #ffd46f`",
            "`--portal-line: rgba(255,212,111,.25)`",
            "restrained ambient glow",
            "deep ink/surface contrast",
            "warm gold primary CTAs",
            "Downloads action pills, download route rows, docs shortcut pills, and OpenAPI endpoint cards",
            'aria-label="Help recovery actions"',
            'aria-label="Contact recovery actions"',
            'aria-label="Status recovery actions"',
            "`Open character roster`, `Open Chummer Online`, `Open Chummer overview`, and `Get desktop client` choices",
            'a.cta[href="/app?command=character_roster"][data-portal-home-action="explore-chummer-online"]',
            "primary portal CTA, not `/blazor/app`",
            "Chummer Online recovery action",
            "Help cards and the help/contact/status rails keep explicit hover/focus affordances",
            "pill-style keyboard-focus treatment",
            "`data-openapi-chummer-app-route=\"true\"`",
            "visible route-family labels",
            ".endpoint-summary",
            "escapeHtml",
            "method-label text",
            "Runtime claims still require the local portal proof and hosted public-edge proof receipts.",
        ],
    },
    {
        "id": "docs_index_contract_link",
        "path": "docs/BLAZOR_WEB_CLIENT_DOCS_INDEX.md",
        "tokens": [
            "Portal Installer Handoff",
            "docs/BLAZOR_PORTAL_INSTALLER_HANDOFF_PROOF.md",
            "scripts/materialize-blazor-portal-installer-handoff-staged-proof.py",
            "scripts/ai/milestones/blazor-portal-installer-handoff-staged-proof-check.sh",
            "portal_installer_handoff_staged_*",
            "direct raw downloads",
            "proof-required handoff rows",
            "self-host operator lane",
            "product-first `Explore Chummer Online` portal root hero",
            "roster-first primary CTA selector",
            "hosted `/blazor/` root redirect that immediately opens the roster-first `app?command=character_roster` browser workflow",
            'a.cta[href="/app?command=character_roster"][data-portal-home-action="explore-chummer-online"]',
            "portal route values centralized through `PortalRoutes.PublicApp`, `PortalRoutes.PublicAppSlash`, `PortalRoutes.PublicAppRoster`, `PortalRoutes.CharacterRosterCommand`, `PortalRoutes.BlazorApp`, `PortalRoutes.BlazorHome`, `PortalRoutes.BlazorAppSegment`, `PortalRoutes.BlazorHomeSegment`, `BuildBlazorAppUrl`, and `BuildBlazorHomeUrl`",
            "data-openapi-chummer-app-route",
            "data-openapi-chummer-home-route",
            "data-openapi-blazor-entry-route",
            "clean public `/app`",
            "data-docs-panel=\"operator-openapi-explorer\"",
            "data-docs-action=\"open-chummer-app\"",
            "clean public `/app?command=character_roster`",
            "Chummer browser routes",
            "same polished Chummer Online slate/amber/mint/blue visual language",
            "restrained ambient glow",
            "deep ink/surface contrast",
            "downloads action pills",
            "download route rows",
            "docs shortcut pills",
            "OpenAPI endpoint cards",
            "portal root rail",
            "hover/focus affordances",
            "reduced-motion handling",
            "help-card hover/focus affordances",
            "labelled help/contact/status recovery rails",
            "help-card plus help/contact/status rail hover/focus affordances",
            "pill-style keyboard-focus treatment",
            "data-docs-action=\"open-downloads\"",
            "data-docs-action=\"open-help\"",
            "data-docs-action=\"open-contact\"",
            "data-docs-action=\"open-openapi-json\"",
            "docs/examples/blazor-portal-installer-handoff-staged-proof.receipt.example.json",
            "It is not runtime proof.",
        ],
    },
    {
        "id": "source_staged_runbook_boundary",
        "path": "docs/BLAZOR_SOURCE_STAGED_PROOF_RUNBOOK.md",
        "tokens": [
            "Adjacent Portal-Boundary Source Proofs",
            "BLAZOR_PORTAL_INSTALLER_HANDOFF_STAGED_PROOF.generated.json",
            "not members of the Chummer Online and /blazor/workbench compatibility route source-staged proof set",
            "they do not prove hosted execution, Docker self-host execution, or installer availability",
            "portal_installer_handoff_staged_status=",
            "portal_installer_handoff_staged_route_count=",
            "portal_installer_handoff_staged_source_checks=",
            "portal_installer_handoff_staged_note=source_alignment_only_raw_artifacts_and_proof_required_handoffs_not_browser_execution",
            "portal_installer_handoff_staged_visual_contract=source_alignment_only_chummer_app_amber_mint_blue_palette_shared_grid_mobile_softened_high_contrast_motion_user_facing_route_rail_downloads_docs_cards_and_labelled_recovery_rails_not_runtime_visual_proof",
        ],
    },
    {
        "id": "contract_doc_index_requirement",
        "path": "docs/BLAZOR_PORTAL_INSTALLER_HANDOFF_PROOF.md",
        "tokens": [
            "Documentation Index Requirement",
            "docs/BLAZOR_WEB_CLIENT_DOCS_INDEX.md",
            "must not be treated as a browser-workflow receipt or runtime installer proof",
        ],
    },
    {
        "id": "self_host_runbook",
        "path": "docs/BLAZOR_SELF_HOST_RUNBOOK.md",
        "tokens": [
            "Docker",
            "/blazor/home",
            "/blazor/app",
            "/blazor/workbench",
            "downloads",
            "same polished Chummer Online slate/amber/mint/blue visual language",
            "restrained ambient glow",
            "deep ink/surface contrast",
            "warm gold primary calls to action",
            "Chummer browser routes",
            "explicit hover/focus affordances",
            "reduced-motion handling",
            "labelled recovery rails",
            "Help cards plus help, contact, and status exits",
            "reduced-motion guards",
        ],
    },
    {
        "id": "release_signoff_boundary",
        "path": "docs/WORKBENCH_RELEASE_SIGNOFF.md",
        "tokens": [
            "BLAZOR_PORTAL_INSTALLER_HANDOFF_PROOF.md",
            "source-staged",
            "not runtime proof",
            "portal_installer_handoff_staged_*",
            "same polished Chummer Online slate/amber/mint/blue visual language",
            "restrained ambient glow",
            "deep ink/surface contrast",
            "reduced-motion handling",
            "labelled help/contact/status recovery rails",
            "reduced-motion guards",
            "source-check and route counts",
            "release-signoff visibility only",
            "they do not prove portal runtime behavior, installer availability, hosted execution, or Docker self-host execution",
        ],
    },
    {
        "id": "parity_goal_portal_recovery_visual_contract",
        "path": "docs/BLAZOR_WEB_CLIENT_PARITY_GOAL.md",
        "tokens": [
            "portal recovery pages for downloads, docs, help, status, and contact",
            "same polished Chummer Online visual language",
            "restrained ambient glow",
            "deep ink/surface contrast",
            "Chummer browser routes",
            "reduced-motion handling",
            "help/contact/status recovery exits",
            "labelled help/contact/status recovery rails",
            "labelled recovery rails",
            "pill-style keyboard focus",
            "explicit hover/focus affordances",
            "reduced-motion guards",
            "staged portal installer/support handoff posture",
            "polished slate/amber/mint/blue palette",
        ],
    },
    {
        "id": "status_utility_reporting",
        "path": "scripts/print_blazor_public_edge_proof_status.py",
        "tokens": [
            "PORTAL_INSTALLER_HANDOFF_STAGED_PROOF",
            "portal_installer_handoff_staged_status",
            "portal_installer_handoff_staged_contract",
            "portal_installer_handoff_staged_tier",
            "portal_installer_handoff_staged_route_count",
            "portal_installer_handoff_staged_source_checks",
            "portal_installer_handoff_staged_note",
            "portal_installer_handoff_staged_visual_contract",
            "source_alignment_only_raw_artifacts_and_proof_required_handoffs_not_browser_execution",
            "source_alignment_only_chummer_app_amber_mint_blue_palette_shared_grid_mobile_softened_high_contrast_motion_user_facing_route_rail_downloads_docs_cards_and_labelled_recovery_rails_not_runtime_visual_proof",
        ],
    },
    {
        "id": "example_receipt_shape",
        "path": "docs/examples/blazor-portal-installer-handoff-staged-proof.receipt.example.json",
        "tokens": [
            '"contract_name": "chummer6-ui.blazor_portal_installer_handoff_staged_proof"',
            '"proof_tier": "source_staged_no_browser_execution"',
            '"route_lane": "portal_backed_blazor_workbench_handoff"',
            '"missing_tokens": []',
            '"notes": [',
            "Portal visual continuity is source alignment only for Chummer Online amber/mint/blue palette, polished deep ink/surface contrast, restrained ambient glow, Chummer browser routes rail user-facing labels and hover/focus affordances, shared ambient grid texture, mobile-softened grid density, high-contrast portal action affordances, and reduced-motion-safe portal panel reveal, downloads/docs cards, help cards, labelled recovery rails, focus affordances, and reduced-motion guards.",
            "Route probes request the absolute `${baseUrl}/downloads/?next=%2Fdownloads%2Finstall%2Fblazor-desktop-linux-x64-installer&installState=proof_required` URL for direct proof-required guidance.",
            "Runtime evidence remains owned by local portal proof, hosted route-entry proof, and hosted execution proof receipts.",
        ],
    },
]


def read_text(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8-sig")


def main() -> int:
    checks = []
    failures = []

    for check in CHECKS:
        path = check["path"]
        tokens = check["tokens"]
        try:
            text = read_text(path)
        except FileNotFoundError:
            failures.append(f"{path}: missing file")
            checks.append({**check, "status": "failed", "missing_tokens": tokens})
            continue

        missing_tokens = [token for token in tokens if token not in text]
        if missing_tokens:
            failures.append(f"{path}: missing {', '.join(missing_tokens)}")
        checks.append(
            {
                "id": check["id"],
                "path": path,
                "status": "failed" if missing_tokens else "passed",
                "required_token_count": len(tokens),
                "missing_tokens": missing_tokens,
            }
        )

    payload = {
        "contract_name": "chummer6-ui.blazor_portal_installer_handoff_staged_proof",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "status": "failed" if failures else "passed",
        "proof_tier": "source_staged_no_browser_execution",
        "route_lane": "portal_backed_blazor_workbench_handoff",
        "expected_routes": EXPECTED_ROUTES,
        "checks": checks,
        "failures": failures,
        "notes": [
            "This proof is source alignment only for Blazor-to-portal installer/download/support handoff.",
            "Portal visual continuity is source alignment only for Chummer Online amber/mint/blue palette, polished deep ink/surface contrast, restrained ambient glow, Chummer browser routes rail user-facing labels and hover/focus affordances, shared ambient grid texture, mobile-softened grid density, high-contrast portal action affordances, and reduced-motion-safe portal panel reveal, downloads/docs cards, help cards, labelled recovery rails, focus affordances, and reduced-motion guards.",
            "Route probes request the absolute `${baseUrl}/downloads/?next=%2Fdownloads%2Finstall%2Fblazor-desktop-linux-x64-installer&installState=proof_required` URL for direct proof-required guidance.",
            "It does not prove the portal is running or routes execute at runtime.",
            "Runtime evidence remains owned by local portal proof, hosted route-entry proof, and hosted execution proof receipts.",
        ],
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    if failures:
        print("\n".join(failures))
        return 1

    print(f"blazor_portal_installer_handoff_staged_proof:ok {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
