using Chummer.Contracts.Characters;
using Chummer.Contracts.Presentation;
using Chummer.Contracts.Workspaces;

namespace Chummer.Presentation.Overview;

public sealed record CharacterOverviewState(
    bool IsBusy,
    string? Error,
    WorkspaceSessionState Session,
    CharacterWorkspaceId? WorkspaceId,
    IReadOnlyList<OpenWorkspaceState> OpenWorkspaces,
    CharacterProfileSection? Profile,
    CharacterProgressSection? Progress,
    CharacterSkillsSection? Skills,
    CharacterRulesSection? Rules,
    CharacterBuildSection? Build,
    CharacterMovementSection? Movement,
    CharacterAwakeningSection? Awakening,
    string? ActiveTabId,
    string? ActiveActionId,
    string? ActiveSectionId,
    string? ActiveSectionJson,
    IReadOnlyList<SectionRowState> ActiveSectionRows,
    BuildLabConceptIntakeState? ActiveBuildLab,
    BrowseWorkspaceState? ActiveBrowseWorkspace,
    string? LastCommandId,
    string? Notice,
    DesktopDialogState? ActiveDialog,
    DesktopPreferenceState Preferences,
    IReadOnlyList<AppCommandDefinition> Commands,
    IReadOnlyList<NavigationTabDefinition> NavigationTabs,
    bool HasSavedWorkspace,
    WorkspaceDownloadReceipt? PendingDownload = null,
    long PendingDownloadVersion = 0,
    WorkspaceExportReceipt? PendingExport = null,
    long PendingExportVersion = 0,
    WorkspacePrintReceipt? PendingPrint = null,
    long PendingPrintVersion = 0,
    NpcPersonaStudioState? ActiveNpcPersonaStudio = null)
{
    public static CharacterOverviewState Empty { get; } = new(
        IsBusy: false,
        Error: null,
        Session: WorkspaceSessionState.Empty,
        WorkspaceId: null,
        OpenWorkspaces: [],
        Profile: null,
        Progress: null,
        Skills: null,
        Rules: null,
        Build: null,
        Movement: null,
        Awakening: null,
        ActiveTabId: null,
        ActiveActionId: null,
        ActiveSectionId: null,
        ActiveSectionJson: null,
        ActiveSectionRows: [],
        ActiveBuildLab: null,
        ActiveBrowseWorkspace: null,
        LastCommandId: null,
        Notice: null,
        ActiveDialog: null,
        Preferences: DesktopPreferenceState.Default,
        Commands: [],
        NavigationTabs: [],
        HasSavedWorkspace: false,
        PendingDownload: null,
        PendingDownloadVersion: 0,
        PendingExport: null,
        PendingExportVersion: 0,
        PendingPrint: null,
        PendingPrintVersion: 0,
        ActiveNpcPersonaStudio: null);
}
