#!/usr/bin/env bash
set -euo pipefail
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export DOTNET_NOLOGO=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export AVALONIA_TELEMETRY_OPTOUT=1
SCRIPT_DIR_PHYSICAL="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT_PHYSICAL="$(cd "$SCRIPT_DIR_PHYSICAL/../.." && pwd -P)"
REPO_ROOT_ALIAS_CANDIDATE="${CHUMMER_UI_REPO_ROOT_ALIAS:-$REPO_ROOT_PHYSICAL}"
REPO_ROOT="$REPO_ROOT_PHYSICAL"
if [[ -n "$REPO_ROOT_ALIAS_CANDIDATE" && -d "$REPO_ROOT_ALIAS_CANDIDATE" ]]; then
  alias_physical="$(cd "$REPO_ROOT_ALIAS_CANDIDATE" && pwd -P)"
  if [[ "$alias_physical" == "$REPO_ROOT_PHYSICAL" ]]; then
    REPO_ROOT="$(cd -L "$REPO_ROOT_ALIAS_CANDIDATE" && pwd -L)"
  fi
fi
WRITABLE_STATE_ROOT="${WRITABLE_STATE_ROOT:-/tmp/chummer-ai}"
export HOME="${HOME:-$WRITABLE_STATE_ROOT/home}"
export DOTNET_CLI_HOME="${DOTNET_CLI_HOME:-$WRITABLE_STATE_ROOT/.dotnet-cli}"
export NUGET_PACKAGES="${NUGET_PACKAGES:-$REPO_ROOT/.tmp/nuget/packages}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$WRITABLE_STATE_ROOT/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$WRITABLE_STATE_ROOT/.local/share}"
export TMPDIR="${TMPDIR:-$WRITABLE_STATE_ROOT/tmp}"
mkdir -p /tmp/.dotnet/shm "$HOME" "$DOTNET_CLI_HOME" "$NUGET_PACKAGES" "$XDG_CACHE_HOME" "$XDG_DATA_HOME" "$TMPDIR"
