#!/usr/bin/env bash
set -euo pipefail
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export DOTNET_NOLOGO=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export AVALONIA_TELEMETRY_OPTOUT=1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
export CHUMMER_REPO_ROOT="${CHUMMER_REPO_ROOT:-$REPO_ROOT}"
WRITABLE_STATE_ROOT="${WRITABLE_STATE_ROOT:-/tmp/chummer-ai}"
export HOME="${HOME:-$WRITABLE_STATE_ROOT/home}"
export DOTNET_CLI_HOME="${DOTNET_CLI_HOME:-$WRITABLE_STATE_ROOT/.dotnet-cli}"
export NUGET_PACKAGES="${NUGET_PACKAGES:-$REPO_ROOT/.tmp/nuget/packages}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$WRITABLE_STATE_ROOT/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$WRITABLE_STATE_ROOT/.local/share}"
export TMPDIR="${TMPDIR:-$WRITABLE_STATE_ROOT/tmp}"
mkdir -p /tmp/.dotnet/shm "$HOME" "$DOTNET_CLI_HOME" "$NUGET_PACKAGES" "$XDG_CACHE_HOME" "$XDG_DATA_HOME" "$TMPDIR"
